# Generated by Django 3.2.5 on 2021-07-16 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_remove_student_section'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='department',
        ),
        migrations.AddField(
            model_name='course',
            name='grade',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='school.class'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='course_type',
            field=models.CharField(choices=[('Compulsary', 'Compulsary'), ('Optional', 'Optional'), ('Vocational', 'Vocational'), ('Extra Curricular', 'Extra Curricular'), ('Others', 'Others')], max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='caste',
            field=models.CharField(choices=[('Brahmin', 'Brahmin'), ('Chhetri', 'Chhetri'), ('Jana-jati', 'Jana-jati'), ('Dalit', 'Dalit'), ('Muslim', 'Muslim'), ('Christain', 'Christain'), ('Others', 'Others')], max_length=25),
        ),
        migrations.AlterField(
            model_name='student',
            name='dob',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], max_length=10),
        ),
    ]
